version: '3.8'
services:
  mi-cuento-db:
    container_name: mi-cuento-db
    image: postgres:16
    restart: always
    volumes:
      - ./mi-cuento-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-mi-cuento-db}
volumes:
  postgres:
